server_address = 127.0.0.1
port = 30002
name = admin
empty_password = true
disallow_empty_password = false

secure.http_mods = nexus

language = en
default_privs = interact, shout, give

# Nexus identity
nexus.proxy_url = http://127.0.0.1:8090
nexus.world_name = abydos
nexus.galaxy_name = milkyway
nexus.galaxy_label = Milky Way
nexus.galaxy_tier = 1
nexus.world_description = Desert world — arid dunes, first destination
nexus.api_secret = cf85c409f62fc2acaa42b067d16a5fd670ba8aecaafe0b0dfb6fc8ccc0297244
nexus.require_power = true

# Power system
nexus_power.ores = resonite,stellarite

# Worldgen
nexus_worldgen.ruin_spacing = 24

# World manager
nexus_worldmanager.time_speed = 72
nexus_worldmanager.hazards = heat
