server_address = 127.0.0.1
port = 30000
name = admin
empty_password = true
disallow_empty_password = false

# Nexus mod can make HTTP requests to the proxy
secure.http_mods = nexus

# Nexus identity
nexus.proxy_url = http://127.0.0.1:8080
nexus.world_name = earth
nexus.galaxy_name = milkyway
nexus.galaxy_label = Milky Way
nexus.galaxy_tier = 1

# Dev/test settings
max_users = 10
creative_mode = false
nexus.api_secret = cf85c409f62fc2acaa42b067d16a5fd670ba8aecaafe0b0dfb6fc8ccc0297244
nexus.require_power = true
