server_address = 127.0.0.1
port = 30001
name = admin
empty_password = true
disallow_empty_password = false

secure.http_mods = nexus

nexus.proxy_url = http://127.0.0.1:8080
nexus.world_name = proxima
nexus.galaxy_name = andromeda
nexus.galaxy_label = Andromeda
nexus.galaxy_tier = 2

max_users = 10
creative_mode = false
nexus.api_secret = cf85c409f62fc2acaa42b067d16a5fd670ba8aecaafe0b0dfb6fc8ccc0297244
nexus.require_power = true
