server_address = 127.0.0.1
port = 30001
name = admin
empty_password = true
disallow_empty_password = false

secure.http_mods = nexus

language = en
default_privs = interact, shout, give

# Nexus identity
nexus.proxy_url = http://127.0.0.1:8090
nexus.world_name = proxima
nexus.galaxy_name = andromeda
nexus.galaxy_label = Andromeda
nexus.galaxy_tier = 3
nexus.world_description = Alien world — dense biosphere, dangerous fauna
nexus.api_secret = cf85c409f62fc2acaa42b067d16a5fd670ba8aecaafe0b0dfb6fc8ccc0297244
nexus.require_power = true

# Power system
nexus_power.ores = resonite,stellarite,voidium

# Worldgen
nexus_worldgen.ruin_spacing = 16

# World manager
nexus_worldmanager.time_speed = 144
nexus_worldmanager.hazards = toxic_fog
