server_address = 127.0.0.1
port = 30010
name = admin
empty_password = true
disallow_empty_password = false

secure.http_mods = nexus_lobby

language = en

nexus.proxy_url = http://127.0.0.1:8090
nexus.api_secret = cf85c409f62fc2acaa42b067d16a5fd670ba8aecaafe0b0dfb6fc8ccc0297244
nexus_worldmanager.time_speed = 0
